services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16}
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mcp_gateway}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: ${WEB_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/web:latest}
    ports:
      - "80:80"
      - "5234:5234"
    environment:
      - ENV=production
      - TZ=${TZ:-UTC}
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.multi:/app/.env
    depends_on:
      - postgres
      - mcp-gateway
      - mock-server
    restart: unless-stopped

  mcp-gateway:
    image: ${MCP_GATEWAY_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/mcp-gateway:latest}
    ports:
      - "5235:5235"
    environment:
      - ENV=production
      - TZ=${TZ:-UTC}
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.multi:/app/.env
    depends_on:
      - postgres
    restart: unless-stopped

  mock-server:
    image: ${MOCK_USER_SVC_IMAGE:-ghcr.io/mcp-ecosystem/mcp-gateway/mock-server:latest}
    ports:
      - "5236:5236"
    environment:
      - ENV=production
      - TZ=${TZ:-UTC}
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
      - ./.env.multi:/app/.env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
