apiVersion: v1
kind: Secret
metadata:
  name: mcp-gateway-secret
type: Opaque
data:
  open_api_key: {{ .Values.config.OPENAI_API_KEY | b64enc }}
  apiserver_jwt_secret_key: {{ .Values.config.APISERVER_JWT_SECRET_KEY | default (randAlphaNum 30) | b64enc }}