apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
    spec:
      containers:
      - name: mcp-gateway
        imagePullPolicy: IfNotPresent  # 优先使用本地镜像
        image: ghcr.io/amoylab/unla/mcp-gateway:latest
        env:
        - name: ENV
          value: production
        - name: TZ
          value: UTC
        envFrom:
          - configMapRef:
              name: app-env
        ports:
        - containerPort: 5235
        volumeMounts:
        - name: configs
          mountPath: /app/configs
        - name: data
          mountPath: /app/data
      volumes:
      - name: configs
        configMap:
          name: app-configs
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: mcp-gateway
spec:
  type: NodePort
  ports:
    - port: 5235
      targetPort: 5235
      nodePort: 30235
      name: mcp-gateway
    - port: 5245
      targetPort: 5245
      nodePort: 30245
      name: mcp-gateway-notifier
  selector:
    app: mcp-gateway