apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-user
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-user
  template:
    metadata:
      labels:
        app: mock-user
    spec:
      containers:
      - name: mock-user
        imagePullPolicy: IfNotPresent  # 优先使用本地镜像
        image: ghcr.io/amoylab/unla/mock-user:latest
        env:
        - name: ENV
          value: production
        - name: TZ
          value: UTC
        ports:
        - containerPort: 5236
        volumeMounts:
        - name: configs
          mountPath: /app/configs
        - name: data
          mountPath: /app/data
        - name: env-file
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: configs
        configMap:
          name: app-configs
      - name: data
        emptyDir: {}
      - name: env-file
        configMap:
          name: app-env
---
apiVersion: v1
kind: Service
metadata:
  name: mock-user
  namespace: mcp-gateway
spec:
  type: NodePort
  ports:
    - port: 5236
      targetPort: 5236
      nodePort: 30236
  selector:
    app: mock-user