apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: mcp-gateway
        - name: TZ
          value: UTC
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}  # 使用 emptyDir 替代 PVC，但数据会在 Pod 重启后丢失
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mcp-gateway
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432  # 指定一个 30000-32767 之间的端口
  selector:
    app: postgres