apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mcp-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          imagePullPolicy: IfNotPresent  # 优先使用本地镜像
          image: ghcr.io/amoylab/unla/web:latest
          env:
            - name: TZ
              value: UTC
            - name: ENV
              value: production
          envFrom:
            - configMapRef:
                name: app-env
          ports:
            - containerPort: 80
            - containerPort: 5234
          volumeMounts:
            - name: configs
              mountPath: /app/configs
            - name: i18n-files
              mountPath: /app/configs/i18n
            - name: data
              mountPath: /app/data
#            - name: web-env
#              mountPath: /app/.env
#              subPath: .env
      volumes:
        - name: configs
          configMap:
            name: app-configs
        - name: data
          emptyDir: {}
#        - name: web-env
#          configMap:
#            name: web-env
        - name: i18n-files
          configMap:
            name: i18n-config
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: mcp-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: my-web
    - port: 5234
      targetPort: 5234
      nodePort: 30234
      name: my-web-api
  selector:
    app: web